services:
  - type: web
    name: markdown-notes-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CORS_ORIGIN
        value: https://markdown-notes-frontend.onrender.com

  - type: web
    name: markdown-notes-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l 3000
    envVars:
      - key: REACT_APP_API_URL
        value: https://markdown-notes-backend.onrender.com/notes